[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
branch = "main"
upload_to_release = true
changelog_sections = ["Features", "Bug Fixes"]
commit_parser = "semantic_release.history.conventional_commits_parser"