name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install pipenv
      - run: pipenv --python 3
      - run: pipenv install
      - run: pipenv run semantic-release -c .releaserc version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}